// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTKf-4h3Q7hyBsv2fF4EP39xg4Mm6x5w',
    appId: '1:593870442889:web:819d401bd16422aa5ad158',
    messagingSenderId: '593870442889',
    projectId: 'pranomi-6a648',
    authDomain: 'pranomi-6a648.firebaseapp.com',
    storageBucket: 'pranomi-6a648.firebasestorage.app',
    measurementId: 'G-FGFK3PVDXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfTnshPtvFrVHdL4LHwvJQipNUNib0KmY',
    appId: '1:593870442889:android:f41e79a17a5b173c5ad158',
    messagingSenderId: '593870442889',
    projectId: 'pranomi-6a648',
    storageBucket: 'pranomi-6a648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApmYB4sRX5ukrAHc121drkw--Z8cpjSgE',
    appId: '1:593870442889:ios:05d5f3a323ba2e8f5ad158',
    messagingSenderId: '593870442889',
    projectId: 'pranomi-6a648',
    storageBucket: 'pranomi-6a648.firebasestorage.app',
    iosBundleId: 'com.example.pranomiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApmYB4sRX5ukrAHc121drkw--Z8cpjSgE',
    appId: '1:593870442889:ios:05d5f3a323ba2e8f5ad158',
    messagingSenderId: '593870442889',
    projectId: 'pranomi-6a648',
    storageBucket: 'pranomi-6a648.firebasestorage.app',
    iosBundleId: 'com.example.pranomiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTKf-4h3Q7hyBsv2fF4EP39xg4Mm6x5w',
    appId: '1:593870442889:web:acc05c616f7528ec5ad158',
    messagingSenderId: '593870442889',
    projectId: 'pranomi-6a648',
    authDomain: 'pranomi-6a648.firebaseapp.com',
    storageBucket: 'pranomi-6a648.firebasestorage.app',
    measurementId: 'G-0LBCX9HT5W',
  );
}
